# Generated by Django 4.1.5 on 2023-02-16 18:36

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
